"""The pure domain of digline.

No I/O, no imports from other digline packages, callable on its own — including
from Plumbline, which uses this core as a library.
"""

from digline.core.adapters import FromAutoevals, score_from_autoevals
from digline.core.aggregate import (
    F1,
    Accuracy,
    CaseOutcome,
    Label,
    Matrix,
    Precision,
    Recall,
    RunAssertion,
    RunAssertionBase,
)
from digline.core.assertions import (
    Affix,
    AssertionBase,
    Contains,
    CostBudget,
    Equals,
    Faithfulness,
    IsJson,
    JsonSchema,
    LatencyBudget,
    Length,
    Levenshtein,
    LlmRubric,
    NotContains,
    PiiAbsent,
    Regex,
    budget_score,
    error_verdict,
    levenshtein_distance,
)
from digline.core.compare import AssertionDelta, Comparison, Outcome, compare
from digline.core.pii import (
    ITALIAN_PII,
    PiiPattern,
    verify_codice_fiscale,
    verify_iban,
    verify_partita_iva,
)
from digline.core.protocols import Assertion, AsyncJudge, ClaimJudge, Judge
from digline.core.ratio import Ratio, as_ratio, reachable_agreements
from digline.core.run import (
    CaseResult,
    Run,
    config_hash,
    redact,
    run_from_json,
    run_to_json,
)
from digline.core.sampling import Repeated, combine_samples
from digline.core.types import (
    ALL_KINDS,
    CONVERSATION_ONLY,
    NOTHING_EXTRA,
    REDACTED,
    STRUCTURED_ONLY,
    TEXT_ONLY,
    TEXT_OR_CONVERSATION,
    TEXT_OR_STRUCTURED,
    ClaimReply,
    Disclosure,
    EvaluatorInputs,
    JudgeReply,
    Message,
    Output,
    OutputKind,
    Score,
    Status,
    Verdict,
    output_kind,
    travels,
)

__all__ = [
    "ALL_KINDS",
    "ITALIAN_PII",
    "CONVERSATION_ONLY",
    "STRUCTURED_ONLY",
    "TEXT_ONLY",
    "TEXT_OR_CONVERSATION",
    "TEXT_OR_STRUCTURED",
    "F1",
    "Accuracy",
    "Affix",
    "Assertion",
    "AssertionBase",
    "AssertionDelta",
    "AsyncJudge",
    "CaseOutcome",
    "CaseResult",
    "Comparison",
    "Contains",
    "CostBudget",
    "Disclosure",
    "ClaimJudge",
    "ClaimReply",
    "Equals",
    "EvaluatorInputs",
    "Faithfulness",
    "FromAutoevals",
    "IsJson",
    "JsonSchema",
    "Judge",
    "JudgeReply",
    "Label",
    "LatencyBudget",
    "Length",
    "Levenshtein",
    "LlmRubric",
    "Matrix",
    "Message",
    "NOTHING_EXTRA",
    "NotContains",
    "Outcome",
    "PiiAbsent",
    "PiiPattern",
    "Output",
    "OutputKind",
    "REDACTED",
    "Precision",
    "Recall",
    "Ratio",
    "Regex",
    "Repeated",
    "RunAssertion",
    "RunAssertionBase",
    "Run",
    "Score",
    "Status",
    "Verdict",
    "as_ratio",
    "budget_score",
    "combine_samples",
    "compare",
    "config_hash",
    "error_verdict",
    "levenshtein_distance",
    "output_kind",
    "reachable_agreements",
    "redact",
    "run_from_json",
    "run_to_json",
    "score_from_autoevals",
    "travels",
    "verify_codice_fiscale",
    "verify_iban",
    "verify_partita_iva",
]
