"""A decision record and the page it becomes.

Every numbered file in `docs/adr/` is synced to digline.dev as a page, and every
page there needs a line in the site's `nav`. Nothing in this repository says so:
the entry is added in the *other* one, by hand, and the build that notices it is
missing runs after PyPI.

This is the check that pays for itself. ADR 0006 was written, the nav line was
added on digline.dev, and the two were only known to be in step because somebody
ran the site build by hand before tagging.
"""

from __future__ import annotations

from pathlib import Path

from tests._site import nav_lists, require_site_config

ROOT = Path(__file__).resolve().parents[1]


def adr_records() -> list[str]:
    """The decisions that become pages, by the name their page will have.

    Numbered files only, matching the glob `sync-docs.sh` lists them with.
    `index.md` is the one page in that directory nobody adds: the script writes
    it at build time from the records it finds, so it is already in the nav and
    is not a record's responsibility.

    `.stem` is the filename without its extension — the page keeps the name, so
    the record and the nav entry differ only in the directory in front of them.
    """
    return sorted(path.stem for path in (ROOT / "docs" / "adr").glob("[0-9]*.md"))


def test_the_adr_glob_still_finds_the_records() -> None:
    """A guard on the guard: an empty list would make the check below pass over
    nothing and prove nothing."""
    found = adr_records()
    assert len(found) >= 6, found
    assert "index" not in found, "index.md is generated by sync-docs.sh, not written"
    assert all(name[0].isdigit() for name in found), found


def test_every_adr_has_a_page_in_the_site_nav() -> None:
    """An ADR added here needs one line in another repository.

    `sync-docs.sh` copies `docs/adr/<name>.md` to `docs/product/adr/<name>.md`,
    and mkdocs builds `--strict`: a page in the docs tree and not in `nav` is a
    warning, and a warning is a failed build. That build is the last job of
    `publish.yml` and runs *after* PyPI, so the first time anyone sees the
    mistake the version is already spent — the same shape of failure that
    `langchain4j` caused on v0.3.0, from the examples side of the same rule.

    The `docs` job in `ci.yml` catches it too, by running the real build. This
    exists beside it because it names the record and the line to add, in a
    second, instead of leaving a reader to read mkdocs' warning about a path
    they did not write.
    """
    config = require_site_config()
    nav = config.read_text(encoding="utf-8")
    missing = [
        name for name in adr_records() if not nav_lists(nav, f"product/adr/{name}.md")
    ]
    assert not missing, (
        f"docs/adr/{missing[0]}.md becomes the page product/adr/{missing[0]}.md, "
        f"which {config} does not list in its nav — so `mkdocs build --strict` "
        f"fails and the site is not rebuilt. Add, under `- Decisions:`:\n"
        f"          - ADR {missing[0][:4]} — <the decision, in a few words>: "
        f"product/adr/{missing[0]}.md\n"
        f"Missing: {', '.join(missing)}. "
        "If that path is a checkout of your own, it may simply be behind "
        "origin — the entry is added in digline/digline.dev, not here."
    )
