"""A decision record and the page it becomes.

Every numbered file in `docs/adr/` is synced to digline.dev as a page, and every
page there needs a line in the site's `nav`. Nothing in this repository says so:
the entry is added in the *other* one, by hand, and the build that notices it is
missing runs after PyPI.

This is the check that pays for itself. ADR 0006 was written, the nav line was
added on digline.dev, and the two were only known to be in step because somebody
ran the site build by hand before tagging.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from tests._site import nav_lists, require_site_config
from tests.test_example_caps import RELEASED

ROOT = Path(__file__).resolve().parents[1]


def adr_records() -> list[str]:
    """The decisions that become pages, by the name their page will have.

    Numbered files only, matching the glob `sync-docs.sh` lists them with.
    `index.md` is the one page in that directory nobody adds: the script writes
    it at build time from the records it finds, so it is already in the nav and
    is not a record's responsibility.

    `.stem` is the filename without its extension — the page keeps the name, so
    the record and the nav entry differ only in the directory in front of them.
    """
    return sorted(path.stem for path in (ROOT / "docs" / "adr").glob("[0-9]*.md"))


def test_the_adr_glob_still_finds_the_records() -> None:
    """A guard on the guard: an empty list would make the check below pass over
    nothing and prove nothing."""
    found = adr_records()
    assert len(found) >= 6, found
    assert "index" not in found, "index.md is generated by sync-docs.sh, not written"
    assert all(name[0].isdigit() for name in found), found


def test_every_adr_has_a_page_in_the_site_nav() -> None:
    """An ADR added here needs one line in another repository.

    `sync-docs.sh` copies `docs/adr/<name>.md` to `docs/product/adr/<name>.md`,
    and mkdocs builds `--strict`: a page in the docs tree and not in `nav` is a
    warning, and a warning is a failed build. That build is the last job of
    `publish.yml` and runs *after* PyPI, so the first time anyone sees the
    mistake the version is already spent — the same shape of failure that
    `langchain4j` caused on v0.3.0, from the examples side of the same rule.

    The `docs` job in `ci.yml` catches it too, by running the real build. This
    exists beside it because it names the record and the line to add, in a
    second, instead of leaving a reader to read mkdocs' warning about a path
    they did not write.
    """
    config = require_site_config()
    nav = config.read_text(encoding="utf-8")
    missing = [
        name for name in adr_records() if not nav_lists(nav, f"product/adr/{name}.md")
    ]
    assert not missing, (
        f"docs/adr/{missing[0]}.md becomes the page product/adr/{missing[0]}.md, "
        f"which {config} does not list in its nav — so `mkdocs build --strict` "
        f"fails and the site is not rebuilt. Add, under `- Decisions:`:\n"
        f"          - ADR {missing[0][:4]} — <the decision, in a few words>: "
        f"product/adr/{missing[0]}.md\n"
        f"Missing: {', '.join(missing)}. "
        "If that path is a checkout of your own, it may simply be behind "
        "origin — the entry is added in digline/digline.dev, not here."
    )


# ── Whether a record has shipped ───────────────────────────────────────────
#
# The status is the first word of `- Status:`, and digline.dev copies it into
# the Decisions table as written. Nothing decided it: until 2026-09-24 four
# records read `proposed` while their code had been released for over a week
# (0020, 0021 and 0022 in 0.13.0, 0024 from 0.14.0), because nothing moved them
# when the code shipped.
#
# The status is not derived from the code, and that is on purpose — no signal
# in the tree says honestly that a decision is in force. What is checked
# instead is one fact written by hand: `- Shipped:` names the core release the
# record's behaviour first shipped in, or says `unreleased`. A version must be
# a row of `RELEASED`, which is itself checked against the tags, and a record
# with a version cannot still be `proposed`. A record whose code lives in a
# plugin names the core release that published it.
#
# What this cannot see is a record left `unreleased` after its code ships.
# RELEASING.md's "moving the number" sweeps for it at every bump, beside the
# `RELEASED` row this check reads.

#: The words a status may start with. The site copies any word, so a new one —
#: `superseded`, the first time a record is — is added here on purpose.
STATUSES = frozenset({"proposed", "accepted"})

_STATUS = re.compile(r"^- Status:[ \t]*([A-Za-z]+)", re.M)
_SHIPPED = re.compile(r"^- Shipped:[ \t]*(.*?)[ \t]*$", re.M)


def header(text: str) -> str:
    """The lines above a record's first `## `, where its status is stated —
    the same span digline.dev reads the table from."""
    return re.split(r"^## ", text, maxsplit=1, flags=re.M)[0]


def shipped_problems(head: str, released: set[str]) -> list[str]:
    """What is wrong with a record's status and `Shipped:` line; empty if nothing."""
    status = _STATUS.search(head)
    if not status:
        return ["no `- Status: <word>` above the first `## `"]
    word = status.group(1)
    problems: list[str] = []
    if word not in STATUSES:
        problems.append(f"status `{word}` is not one of {sorted(STATUSES)}")
    shipped = _SHIPPED.findall(head)
    if len(shipped) != 1:
        return [
            *problems,
            f"{len(shipped)} `- Shipped:` lines above the first `## `, not 1",
        ]
    value = shipped[0]
    if value == "unreleased":
        return problems
    if value not in released:
        problems.append(
            f"`Shipped: {value}` names no release in RELEASED; write a core "
            "version that has been tagged, or `unreleased`"
        )
    elif word == "proposed":
        problems.append(
            f"`Shipped: {value}` and still `proposed`: a record whose behaviour is "
            "in a released version is in force"
        )
    return problems


def test_every_record_says_whether_it_has_shipped() -> None:
    found = {
        name: shipped_problems(
            header((ROOT / "docs" / "adr" / f"{name}.md").read_text(encoding="utf-8")),
            set(RELEASED),
        )
        for name in adr_records()
    }
    wrong = {name: problems for name, problems in found.items() if problems}
    assert not wrong, "\n".join(
        f"docs/adr/{name}.md: {'; '.join(problems)}" for name, problems in wrong.items()
    )


_VALID = (
    "# ADR 0099 — T\n\n"
    "- Status: accepted — the text first\n"
    "- Shipped: 0.13.0\n"
    "- Date: 2026-09-15\n\n"
    "## Context\n"
)


def test_the_valid_header_the_controls_start_from_passes() -> None:
    """Each control below is this header with one field changed, so a control
    that fails is failing on that field and on nothing else."""
    assert shipped_problems(header(_VALID), {"0.13.0"}) == []
    unreleased = _VALID.replace("0.13.0", "unreleased")
    assert shipped_problems(header(unreleased), set()) == []
    assert (
        shipped_problems(header(unreleased.replace("accepted", "proposed")), set())
        == []
    )


@pytest.mark.parametrize(
    ("label", "text", "needle"),
    [
        (
            "proposed after its release",
            _VALID.replace("accepted", "proposed"),
            "still `proposed`",
        ),
        (
            "a version never released",
            _VALID.replace("0.13.0", "0.99.0"),
            "names no release",
        ),
        (
            "no Shipped line",
            _VALID.replace("- Shipped: 0.13.0\n", ""),
            "0 `- Shipped:` lines",
        ),
        ("an empty Shipped line", _VALID.replace(" 0.13.0", ""), "names no release"),
        (
            "two Shipped lines",
            _VALID.replace("- Date:", "- Shipped: 0.13.0\n- Date:"),
            "2 `- Shipped:`",
        ),
        (
            "a Shipped line only below the first ##",
            _VALID.replace("- Shipped: 0.13.0\n", "") + "- Shipped: 0.13.0\n",
            "0 `- Shipped:` lines",
        ),
        (
            "a status word nobody uses",
            _VALID.replace("accepted", "aceppted"),
            "is not one of",
        ),
    ],
)
def test_a_header_one_field_from_valid_is_refused(
    label: str, text: str, needle: str
) -> None:
    problems = shipped_problems(header(text), {"0.13.0"})
    assert any(needle in problem for problem in problems), (label, problems)
