"""The report: a comparison rendered for the reader who does not read code.

Pure functions — the caller writes the file. Depends on `digline.core` and on
nothing else in digline.
"""

from digline.report import diff, explain, pages
from digline.report.explain import (
    CheckFact,
    Fact,
    SettingFact,
    TallyFact,
    explain_text,
    facts,
)
from digline.report.history import CaseEntry, CaseHistory, case_history
from digline.report.log import (
    IdentityLog,
    IdentitySpan,
    Reference,
    Replay,
    Roll,
    Sighting,
    identity_log,
    log_text,
)
from digline.report.pages import (
    VIEW_CSS,
    case_page,
    compare_page,
    fmt3,
    human_time,
    runs_page,
    suspend_page,
    suspension_snippet,
)
from digline.report.render import (
    RUN_SECTIONS,
    SECTIONS,
    SUMMARY_OUTCOMES,
    ErroredVerdict,
    Headline,
    RunTally,
    Section,
    artifact_lines,
    calibration_fact,
    check_line,
    config_changes,
    config_lines,
    diff_lines,
    diff_tally,
    errored_verdicts,
    escape,
    headline,
    render_html,
    render_run_html,
    run_tally,
    scale_lost,
    summary_lines,
    suspended_cases,
    unjudged_cases,
    visible,
)
from digline.report.text import LOCALES, TEXT, Locale, phrase

__all__ = [
    "LOCALES",
    "VIEW_CSS",
    "CaseEntry",
    "CaseHistory",
    "CheckFact",
    "Fact",
    "SettingFact",
    "TallyFact",
    "RUN_SECTIONS",
    "SECTIONS",
    "SUMMARY_OUTCOMES",
    "TEXT",
    "ErroredVerdict",
    "Headline",
    "IdentityLog",
    "IdentitySpan",
    "Locale",
    "Reference",
    "Replay",
    "Roll",
    "RunTally",
    "Section",
    "Sighting",
    "case_history",
    "identity_log",
    "log_text",
    "calibration_fact",
    "check_line",
    "diff",
    "case_page",
    "config_changes",
    "config_lines",
    "compare_page",
    "fmt3",
    "artifact_lines",
    "diff_lines",
    "diff_tally",
    "headline",
    "human_time",
    "pages",
    "phrase",
    "render_html",
    "render_run_html",
    "errored_verdicts",
    "explain",
    "explain_text",
    "facts",
    "run_tally",
    "runs_page",
    "summary_lines",
    "suspend_page",
    "suspended_cases",
    "suspension_snippet",
    "unjudged_cases",
    "scale_lost",
    "escape",
    "visible",
]
