"""File-based store: `.digline/` inside the user's repository.

    .digline/
      config.yaml                          versioned
      <tenant>/baselines/<suite>.json      versioned  <- the local comparison
      <tenant>/runs/<suite>/*.json         ignored       no competitor has
      .gitignore                           generated, contains "*/runs/"

The verdict and its history are an artifact of the project: read in a code
review, anchored to a commit, moving with the repository.

The tenant is a directory and not a field inside the file, so the separation
between perimeters is something the filesystem enforces rather than something a
document merely describes.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
from collections.abc import Mapping, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import cast

from digline.core.run import SCHEMA_VERSION, Run, run_from_json, run_to_json
from digline.store.protocol import (
    ConfigMismatchError,
    ErroredRunError,
    Listing,
    RunRef,
    TenantMismatchError,
)

__all__ = ["FileResultStore", "utc_now_iso"]

STORE_DIRNAME = ".digline"
_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
_GITIGNORE = (
    "# Generated by digline. Run artifacts are ephemeral;\n"
    "# baselines under <tenant>/baselines/ are meant to be committed.\n"
    "*/runs/\n"
)


def utc_now_iso() -> str:
    """UTC timestamp truncated to the second. It lives here and not in the core
    because reading the clock is I/O: the core stays pure and its tests stay
    deterministic."""
    return datetime.now(UTC).replace(microsecond=0).isoformat()


def _check_name(value: str, kind: str) -> str:
    """Reject anything that is not a single safe path segment.

    `..` and `/` are the interesting rejections: a tenant is a directory, so a
    name that could climb out of it would defeat the separation the layout
    exists to provide.
    """
    if not _NAME_RE.match(value):
        raise ValueError(
            f"invalid {kind} name: {value!r} "
            "(letters, digits, dot, dash and underscore are allowed)"
        )
    return value


def _slug(created_at: str) -> str:
    """Rende an ISO timestamp usable as a filename on every system: colons are
    legal on macOS and Linux but not on Windows."""
    return re.sub(r"[^0-9A-Za-z]+", "-", created_at).strip("-")


def _write_atomic(path: Path, payload: str) -> None:
    """Write through a temporary file and `os.replace`, which is atomic on the
    same filesystem: an interruption never leaves a half-written baseline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


class FileResultStore:
    """The default `ResultStore` implementation."""

    def __init__(self, project_root: Path | str) -> None:
        self.root = Path(project_root).resolve() / STORE_DIRNAME

    def tenant_dir(self, tenant: str) -> Path:
        return self.root / _check_name(tenant, "tenant")

    def baselines_dir(self, tenant: str) -> Path:
        return self.tenant_dir(tenant) / "baselines"

    def runs_dir(self, tenant: str) -> Path:
        return self.tenant_dir(tenant) / "runs"

    def ensure_layout(self, tenant: str) -> None:
        """Create the structure for one perimeter and the shared `.gitignore`.
        Idempotent, and it does not overwrite a `.gitignore` the user edited."""
        self.baselines_dir(tenant).mkdir(parents=True, exist_ok=True)
        self.runs_dir(tenant).mkdir(parents=True, exist_ok=True)
        gitignore = self.root / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(_GITIGNORE, encoding="utf-8")

    def baseline_path(self, tenant: str, suite: str) -> Path:
        return self.baselines_dir(tenant) / f"{_check_name(suite, 'suite')}.json"

    def run_path(self, ref: RunRef) -> Path:
        return (
            self.runs_dir(ref.tenant)
            / _check_name(ref.suite, "suite")
            / f"{ref.key}.json"
        )

    @staticmethod
    def key_for(run: Run) -> str:
        """The key a run is filed under. Public because listing has to be able
        to say which stored run the baseline was made from, and recomputing the
        rule in two places is how the two answers start to differ."""
        return f"{_slug(run.created_at)}-{run.config_hash}"

    def write_run(self, run: Run) -> RunRef:
        self.ensure_layout(run.tenant)
        ref = RunRef(
            tenant=_check_name(run.tenant, "tenant"),
            suite=_check_name(run.suite, "suite"),
            key=self.key_for(run),
        )
        _write_atomic(self.run_path(ref), run_to_json(run))
        return ref

    def list_runs(self, tenant: str, suite: str) -> Sequence[RunRef]:
        """Every stored run of this suite in this perimeter, key-ordered.

        The key begins with the slugged timestamp, so key order is chronological
        order — but a caller that wants to *show* a date should read the run and
        use its `created_at`, which is the recorded fact rather than a filename.
        """
        directory = self.runs_dir(tenant) / _check_name(suite, "suite")
        if not directory.is_dir():
            return ()
        return tuple(
            RunRef(tenant=tenant, suite=suite, key=path.stem)
            for path in sorted(directory.glob("*.json"))
        )

    def scan_runs(self, tenant: str, suite: str) -> Listing:
        """`list_runs`, but reading only each file's declared schema version.

        Ordered by filename, which is chronological because the key begins with
        the slugged timestamp — and, more to the point here, because ordering
        by `created_at` would mean building a `Run` from every file, including
        the ones this version cannot build a `Run` from at all.

        Only `schema_version` is read from each document. A file is opened, but
        nothing is constructed from it: that is what lets a foreign schema be
        counted instead of raising.
        """
        directory = self.runs_dir(tenant) / _check_name(suite, "suite")
        if not directory.is_dir():
            return Listing(runs=())

        keep: list[RunRef] = []
        skipped: dict[int, int] = {}
        unreadable: list[str] = []
        for path in sorted(directory.glob("*.json")):
            try:
                raw = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                unreadable.append(path.name)
                continue
            if not isinstance(raw, dict):
                # Valid JSON, but not a document: a list or a bare number is as
                # unusable here as a truncated file.
                unreadable.append(path.name)
                continue
            # `json.loads` returns `Any`; narrowing once here is what keeps the
            # rest of the loop checkable.
            document = cast(Mapping[str, object], raw)
            version = int(cast(int, document.get("schema_version", 0)))
            if version == SCHEMA_VERSION:
                keep.append(RunRef(tenant=tenant, suite=suite, key=path.stem))
            else:
                skipped[version] = skipped.get(version, 0) + 1
        return Listing(runs=tuple(keep), skipped=skipped, unreadable=tuple(unreadable))

    def run_paths(self, tenant: str, suite: str) -> tuple[Path, ...]:
        """Every stored run file of a suite, readable or not.

        Migration needs the files themselves, not the runs: a document this
        version cannot parse is exactly the one that has to be migrated.
        """
        directory = self.runs_dir(tenant) / _check_name(suite, "suite")
        if not directory.is_dir():
            return ()
        return tuple(sorted(directory.glob("*.json")))

    def read_run(self, ref: RunRef) -> Run:
        path = self.run_path(ref)
        if not path.exists():
            raise FileNotFoundError(f"run not found: {path}")
        run = run_from_json(path.read_text(encoding="utf-8"))
        if run.tenant != ref.tenant:
            raise TenantMismatchError(
                f"the run stored at {path} declares tenant {run.tenant!r} but "
                f"was addressed as {ref.tenant!r}"
            )
        return run

    def read_baseline(self, tenant: str, suite: str) -> Run | None:
        path = self.baseline_path(tenant, suite)
        if not path.exists():
            return None
        run = run_from_json(path.read_text(encoding="utf-8"))
        if run.tenant != tenant:
            raise TenantMismatchError(
                f"the baseline at {path} declares tenant {run.tenant!r} but was "
                f"read as {tenant!r}"
            )
        return run

    def promote_baseline(self, ref: RunRef, expected_config_hash: str) -> Run:
        # `read_run` already refuses a run addressed through the wrong tenant.
        run = self.read_run(ref)
        if run.config_hash != expected_config_hash:
            raise ConfigMismatchError(
                f"run {ref.key} was produced with config_hash "
                f"{run.config_hash}, the current configuration is "
                f"{expected_config_hash}: promoting it would record scores "
                "obtained under a configuration other than the one in force"
            )

        errored = sorted(
            {
                case.case_id
                for case in run.results
                for verdict in case.verdicts
                if verdict.status == "error"
            }
        )
        if errored:
            raise ErroredRunError(
                f"run {ref.key} could not judge {len(errored)} case(s) "
                f"({', '.join(errored)}): a baseline is an approved reference "
                "and an error is not one. Fix the case or remove it from the "
                "suite; promoting it would freeze a red line no reader could "
                "tell apart from a new failure"
            )

        self.ensure_layout(run.tenant)
        _write_atomic(self.baseline_path(run.tenant, run.suite), run_to_json(run))
        return run
