"""File-based store: `.digline/` inside the user's repository.

    .digline/
      config.yaml                          versioned
      <tenant>/baselines/<suite>.json      versioned  <- the local comparison
      <tenant>/register/<suite>.jsonl      versioned  <- what a person decided
      <tenant>/runs/<suite>/*.json         ignored       no competitor has
      .gitignore                           generated, contains "*/runs/"
      .gitattributes                       generated, the register merges by union

The verdict and its history are an artifact of the project: read in a code
review, anchored to a commit, moving with the repository.

The tenant is a directory and not a field inside the file, so **addressing** is
something the filesystem enforces rather than something a document merely
describes: filing or reading one client's history as another's is a refused
mistake. It is not access control. Nothing here sets or inspects a mode, and one
OS user reads every tenant; separating access is the operator's job (fixed
decision 8).
"""

from __future__ import annotations

import errno
import fnmatch
import glob
import json
import os
import re
import tempfile
from collections.abc import Mapping, Sequence
from contextlib import suppress
from dataclasses import dataclass, replace
from pathlib import Path
from typing import cast

from digline.core.refused import Quoted
from digline.core.register import (
    DISPOSITIONS,
    RecordedOutcome,
    RegisterEntry,
)
from digline.core.run import (
    SCHEMA_VERSION,
    CallTotals,
    CaseProgress,
    CaseResult,
    DocumentRefusedError,
    Run,
    SystemConfig,
    case_from_dict,
    case_to_dict,
    config_from_dict,
    config_to_dict,
    declared_boolean,
    declared_integer,
    declared_version,
    key_of,
    run_from_json,
    run_to_json,
    totals_from_dict,
    totals_to_dict,
    without_responses,
)
from digline.core.types import Cause
from digline.store.deletion import refusal_for_a_promoted_run
from digline.store.promotion import (
    refusal_for_a_moved_baseline,
    refusals_for,
)
from digline.store.protocol import (
    JOURNAL_VERSION,
    REGISTER_VERSION,
    DirectoryUnreadableError,
    Filing,
    JournalBusyError,
    JournalHeader,
    KeylessRunError,
    Listing,
    Misfiled,
    MisfiledRunError,
    NotAReferenceError,
    PathRefusedError,
    Pending,
    Register,
    RegisterRefusedError,
    Removal,
    RemovedRun,
    RunNotFoundError,
    RunRef,
    SuiteMismatchError,
    TenantMismatchError,
)

__all__ = [
    "NAME_TABLE_DIRNAME",
    "PENDING_DIRNAME",
    "REGISTER_DIRNAME",
    "FileJournal",
    "FileResultStore",
    "journal_key",
]

STORE_DIRNAME = ".digline"
_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
_GITIGNORE = (
    "# Generated by digline. Run artifacts are ephemeral;\n"
    "# baselines under <tenant>/baselines/ are meant to be committed.\n"
    "*/runs/\n"
    "# The name table is the re-identification key, and never committed.\n"
    "*/name-table/\n"
)
#: Two branches that each record a disposition meet at the end of the file,
#: which is the one place a line-based merge always conflicts. Git's union
#: driver keeps both sides' lines, and the reader orders by `recorded_at` rather
#: than by file order. (ADR 0021 §4)
_GITATTRIBUTES = (
    "# Generated by digline. The register is append-only, so two branches that\n"
    "# each added a line keep both when they merge.\n"
    "*/register/*.jsonl merge=union\n"
)

#: Where the register lives: beside `baselines/` and committed like it, because
#: it is a person's record. Not under `runs/` and not under `decisions/`, so the
#: generated `.gitignore` tracks it without a rule of its own. (ADR 0021 §4)
REGISTER_DIRNAME = "register"

#: The name table's place in the tenant's directory, reserved for the process
#: that owns the table. digline writes nothing under it and reads nothing from
#: it: the files inside, their format and their lock are that process's. It is a
#: directory and not a file name because a table kept in SQLite is at times
#: several files — `-journal`, `-wal` and `-shm` beside the database — and a
#: directory covers every one of them, and any other engine's, by construction.
#: Nothing digline writes can land here, because every other path in the layout
#: goes through `baselines/`, `runs/` or `register/`. (ADR 0036 §2)
NAME_TABLE_DIRNAME = "name-table"


def _check_name(value: str, kind: str) -> str:
    """Reject anything that is not a single safe path segment.

    `..` and `/` are the interesting rejections: a tenant is a directory, so a
    name that could climb out of it would defeat the addressing the layout
    exists to provide.
    """
    if not _NAME_RE.match(value):
        raise PathRefusedError(
            f"invalid {kind} name: {value!r} "
            "(letters, digits, dot, dash and underscore are allowed)"
        )
    return value


def _declared_key(document: Mapping[str, object]) -> str | None:
    """`key_of` of the document's own two fields, or `None` when either is
    missing, not a string, or empty. Read from the parsed object: nothing is
    validated, and no `Run` is built. (ADR 0040 §5.2)"""
    created_at = document.get("created_at")
    config_hash = document.get("config_hash")
    if not isinstance(created_at, str) or not isinstance(config_hash, str):
        return None
    if not created_at or not config_hash:
        return None
    return key_of(created_at, config_hash)


def _misfiled(
    named_otherwise: list[tuple[str, str]], stems: set[str]
) -> tuple[Misfiled, ...]:
    """Each left-out file, with the facts about the directory its sentence
    needs: is a file named by its key there, and how many left-out files hold
    that same key where none is. (ADR 0040 §5.1, §5.3)"""
    holders: dict[str, int] = {}
    for _stem, key in named_otherwise:
        holders[key] = holders.get(key, 0) + 1
    return tuple(
        Misfiled(
            stem=stem,
            key=key,
            taken=key in stems,
            safe=bool(_NAME_RE.match(key)),
            sharing=1 if key in stems else holders[key],
        )
        for stem, key in named_otherwise
    )


def _write_atomic(path: Path, payload: str) -> None:
    """Write through a temporary file and `os.replace`, which is atomic on the
    same filesystem: an interruption never leaves a half-written baseline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


#: The errors that mean a path is not there, as `Path.exists` read them on 3.12
#: and 3.13. Python 3.14 reads *every* `OSError` as "not there", so a baseline
#: inside a directory that cannot be searched became no baseline. (#365)
_ABSENT = frozenset({errno.ENOENT, errno.ENOTDIR, errno.EBADF, errno.ELOOP})


def _document_text(path: Path) -> str:
    """A stored run or baseline as text, or a refusal naming the byte that is
    not UTF-8.

    Bare, the `UnicodeDecodeError` is a `ValueError`, and since ADR 0041 §4.2 a
    bare `ValueError` that reaches a front end exits 70, *"not anticipated"*.
    A file somebody edited or corrupted is the document's fault, so it is named
    at the read, where it happens, and not by a rule in `main()` that would also
    catch a decode error inside digline itself.
    """
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        raise DocumentRefusedError(
            f"{path} is not UTF-8 at byte {exc.start}: digline writes a run "
            "document as UTF-8, so these bytes are not one"
        ) from None


def _exists(path: Path) -> bool:
    """`path.exists()`, except that "could not look" is a refusal, not `False`.

    On 3.12 and 3.13 that case raised a bare `PermissionError`, which reached a
    person as a traceback. On 3.14 it returned `False`, and nothing at all
    reached anyone.
    """
    try:
        path.stat()
    except OSError as exc:
        if exc.errno in _ABSENT:
            return False
        raise DirectoryUnreadableError(
            f"cannot tell whether {path} exists: "
            f"{exc.strerror or f'errno {exc.errno}'}. It was not read, so this is "
            "not a missing file"
        ) from exc
    return True


def _listed(directory: Path, pattern: str) -> list[Path]:
    """The entries of `directory` matching `pattern`, sorted, or a refusal.

    `directory.glob(pattern)` returned the same entries, and returned none when
    the directory could not be opened: its own `os.scandir` raised and glob
    caught it. Listing through `os.scandir` here keeps the `OSError` it raises.
    `fnmatch.filter` matches the way `Path.glob` does, case included.

    An absent directory is an empty list, as it was. It replaces an `is_dir()`
    check that answered `False` on 3.14 for a directory nobody could search.
    (#365)
    """
    try:
        with os.scandir(directory) as entries:
            names = [entry.name for entry in entries]
    except OSError as exc:
        if exc.errno in _ABSENT:
            return []
        raise DirectoryUnreadableError(
            f"cannot list {directory}: {exc.strerror or f'errno {exc.errno}'}. "
            "Nothing in it was read, so this is not an empty directory"
        ) from exc
    return sorted(directory / name for name in fnmatch.filter(names, pattern))


def _suite_dirs(runs: Path) -> list[Path]:
    """Every suite directory under a tenant's `runs/`, sorted, or a refusal.

    `_listed`'s rule for a directory that cannot be opened: a tenant whose
    `runs/` could not be listed was not looked at, which is not a tenant with
    no runs. An entry whose name is not one safe segment is no suite any
    reader can address, so it is not one here either. (ADR 0044 §3.4)
    """
    try:
        with os.scandir(runs) as entries:
            names = [entry.name for entry in entries if entry.is_dir()]
    except OSError as exc:
        if exc.errno in _ABSENT:
            return []
        raise DirectoryUnreadableError(
            f"cannot list {runs}: {exc.strerror or f'errno {exc.errno}'}. "
            "Nothing in it was read, so this is not a tenant with no runs"
        ) from exc
    return sorted(runs / name for name in names if _NAME_RE.match(name))


def _keyless(document: Mapping[str, object]) -> str:
    """Why `_declared_key` found no key, field by field, or empty when it did.

    Named rather than summed up, because a person repairs a field: *"it lacks
    created_at"* says what to put back, *"it has no key"* does not."""
    why: list[str] = []
    for name in ("created_at", "config_hash"):
        value = document.get(name, _MISSING)
        if value is _MISSING:
            why.append(f"it lacks {name}")
        elif not isinstance(value, str):
            why.append(f"its {name} is {_kind(value)}, not a string")
        elif not value:
            why.append(f"its {name} is empty")
    return " and ".join(why)


def _declared(document: Mapping[str, object], name: str, filed: str) -> str:
    """The tenant or suite a document declares, or the directory it was filed
    in when it declares none that is a string: there is then no other address
    to name it by. `filed_as` still records the filing, because a declaration
    that is missing is a malformed document. (ADR 0044 §3.4)"""
    value = document.get(name)
    return value if isinstance(value, str) and value else filed


def _shown(value: object) -> str:
    """A declared value in a refusal: quoted when it is a string, named by its
    JSON kind when not, and never longer than a reader needs."""
    return repr(value[:60]) if isinstance(value, str) else _kind(value)


def _rejudged_from(document: Mapping[str, object]) -> str | None:
    """The key a document says it replays, or `None`. A value that is not a
    string names no key, so it puts the document on no chain."""
    value = document.get("rejudged_from")
    return value if isinstance(value, str) else None


def _header_created_at(leg: Path) -> str | None:
    """The `created_at` a leg's header carries, or `None` where it cannot be
    read: a run a delete removes as legs alone has nowhere else to say when it
    was born. Read, never trusted further than that. (ADR 0044 §6)"""
    try:
        with leg.open(encoding="utf-8") as handle:
            raw = json.loads(handle.readline())
    except (OSError, ValueError):
        return None
    if not isinstance(raw, dict):
        return None
    header = cast(Mapping[str, object], raw)
    created_at = header.get("created_at")
    if header.get("kind") != "header" or not isinstance(created_at, str):
        return None
    return created_at or None


@dataclass(frozen=True, slots=True)
class _Doomed:
    """One run on a delete's plan: what the caller is told, and the paths that
    go. The paths are the names found in the directories, never the files
    they resolve to, so a link inside the store is removed and its target is
    not."""

    removed: RemovedRun
    legs: tuple[Path, ...]
    document: Path | None


class FileResultStore:
    """The default `ResultStore` implementation."""

    def __init__(self, project_root: Path | str) -> None:
        self.root = Path(project_root).resolve() / STORE_DIRNAME

    def _inside(self, path: Path, kind: str) -> Path:
        """The file a checked name led to, verified to be inside the store.

        `_check_name` proves a *name* is one safe segment. It cannot prove
        where that name leads, and until 0.7.2 nothing did: a symlink placed
        inside `.digline/` under a perfectly legal key —
        `planted-key.json -> ../../../../outside/evil.json` — passed every
        check, and `digline view`, `digline compare` and the MCP `get_run` all
        read it and rendered what came back.

        Both sides are resolved, so a `.digline` that is *itself* a symlink —
        a store kept on another volume — stays legitimate: what is refused is
        leaving the store, not reaching it by a link.
        """
        resolved = path.resolve()
        if not resolved.is_relative_to(self.root.resolve()):
            raise PathRefusedError(
                f"the {kind} at {path.name} resolves to {resolved}, which is "
                f"outside {self.root}. A name that passes the segment check can "
                "still be a link out of the store, so the file it reaches is "
                "checked too — the run documents digline reads are the ones it "
                "wrote, inside the perimeter that owns them."
            )
        return resolved

    def tenant_dir(self, tenant: str) -> Path:
        return self.root / _check_name(tenant, "tenant")

    def name_table_dir(self, tenant: str) -> Path:
        """The directory the process that owns this tenant's name table keeps
        it in: `.digline/<tenant>/name-table/`.

        The one path in the layout digline hands out and never uses. It is not
        created and not resolved here, and nothing under it is read: whether it
        exists, what is in it and whether it is a link are the owning process's.
        The tenant is checked as every tenant is, so a name that could climb out
        of the store is refused before a path is built. (ADR 0036 §2)
        """
        return self.tenant_dir(tenant) / NAME_TABLE_DIRNAME

    def baselines_dir(self, tenant: str) -> Path:
        return self.tenant_dir(tenant) / "baselines"

    def runs_dir(self, tenant: str) -> Path:
        return self.tenant_dir(tenant) / "runs"

    def ensure_layout(self, tenant: str) -> None:
        """Create the structure for one perimeter and the shared `.gitignore`
        and `.gitattributes`. Idempotent, and it overwrites neither file when the
        user has one."""
        self.baselines_dir(tenant).mkdir(parents=True, exist_ok=True)
        self.runs_dir(tenant).mkdir(parents=True, exist_ok=True)
        gitignore = self.root / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(_GITIGNORE, encoding="utf-8")
        gitattributes = self.root / ".gitattributes"
        if not gitattributes.exists():
            gitattributes.write_text(_GITATTRIBUTES, encoding="utf-8")

    def baseline_path(self, tenant: str, suite: str) -> Path:
        return self.baselines_dir(tenant) / f"{_check_name(suite, 'suite')}.json"

    def run_path(self, ref: RunRef) -> Path:
        # The key is checked like the other two segments, and for a sharper
        # reason: tenant and suite come from a suite the developer wrote, while
        # the key is the one segment that arrives from outside — `--run` on the
        # command line, `?run=` in the view's query string. It was once the only
        # part of this path taken verbatim, and `?run=../../../elsewhere` then
        # read a file outside `.digline/` and the view rendered it.
        return (
            self.runs_dir(ref.tenant)
            / _check_name(ref.suite, "suite")
            / f"{_check_name(ref.key, 'run')}.json"
        )

    def write_run(self, run: Run) -> RunRef:
        self.ensure_layout(run.tenant)
        ref = RunRef(
            tenant=_check_name(run.tenant, "tenant"),
            suite=_check_name(run.suite, "suite"),
            key=key_of(run.created_at, run.config_hash),
        )
        _write_atomic(self.run_path(ref), run_to_json(run))
        return ref

    def list_runs(self, tenant: str, suite: str) -> Sequence[RunRef]:
        """Every stored run of this suite in this perimeter, key-ordered.

        The key begins with the slugged timestamp, so key order is chronological
        order — but a caller that wants to *show* a date should read the run and
        use its `created_at`, which is the recorded fact rather than a filename.
        """
        directory = self.runs_dir(tenant) / _check_name(suite, "suite")
        return tuple(
            RunRef(tenant=tenant, suite=suite, key=path.stem)
            for path in _listed(directory, "*.json")
        )

    def scan_runs(self, tenant: str, suite: str) -> Listing:
        """`list_runs`, but reading only each file's declared schema version.

        Ordered by filename, which is chronological because the key begins with
        the slugged timestamp — and, more to the point here, because ordering
        by `created_at` would mean building a `Run` from every file, including
        the ones this version cannot build a `Run` from at all.

        Only `schema_version`, `created_at` and `config_hash` are read from
        each document. A file is opened, but nothing is constructed from it:
        that is what lets a foreign schema be counted instead of raising.

        **A file whose name is not its run's key is left out first**, before
        its schema is looked at: a file at an old schema with the wrong name
        still has the wrong name, and `migrate` would rewrite it under that
        name. Its key is `key_of` of the two fields, and no `Run` is built
        from it. A document that lacks either field is not checked here and
        goes on as it did before, to be refused by the read. (ADR 0040 §4,
        §5; the last case is open there, and left as it was by ruling.)
        """
        directory = self.runs_dir(tenant) / _check_name(suite, "suite")
        keep: list[RunRef] = []
        skipped: dict[int, int] = {}
        unreadable: list[str] = []
        named_otherwise: list[tuple[str, str]] = []
        paths = _listed(directory, "*.json")
        for path in paths:
            try:
                # The same rule as `read_run`, and here it decides whether a
                # file is *opened* at all: a linked-out run is counted
                # unreadable rather than parsed.
                raw = json.loads(self._inside(path, "run").read_text(encoding="utf-8"))
            except (OSError, ValueError, json.JSONDecodeError):
                unreadable.append(path.name)
                continue
            if not isinstance(raw, dict):
                # Valid JSON, but not a document: a list or a bare number is as
                # unusable here as a truncated file.
                unreadable.append(path.name)
                continue
            # `json.loads` returns `Any`; narrowing once here is what keeps the
            # rest of the loop checkable.
            document = cast(Mapping[str, object], raw)
            key = _declared_key(document)
            if key is not None and key != path.stem:
                named_otherwise.append((path.stem, key))
                continue
            try:
                version = declared_version(document)
            except ValueError:
                # A version that is not an integer has no schema to be counted
                # under and nothing that recovers it, so `skipped` — whose
                # advice points at `migrate` or an upgrade — would be false.
                # It is a document this version cannot place. (#350)
                unreadable.append(path.name)
                continue
            if version == SCHEMA_VERSION:
                keep.append(RunRef(tenant=tenant, suite=suite, key=path.stem))
            else:
                skipped[version] = skipped.get(version, 0) + 1
        return Listing(
            runs=tuple(keep),
            skipped=skipped,
            unreadable=tuple(unreadable),
            misfiled=_misfiled(named_otherwise, {path.stem for path in paths}),
        )

    def run_paths(self, tenant: str, suite: str) -> tuple[Path, ...]:
        """Every stored run file of a suite, readable or not — and every one
        proved to lead inside the store.

        Migration needs the files themselves, not the runs: a document this
        version cannot parse is exactly the one that has to be migrated.

        **The one lister that had no `_inside`, and the one whose caller
        writes.** `scan_runs` beside it counts a linked-out file as unreadable;
        this returned it, and `migrate` read the document through the link and
        wrote the upgraded one back through it — outside the repository, exit
        0, reported as an ordinary "migrated". So a link that leaves the store
        refuses the listing, by name, before anything is read or written:
        unlike a document that will not parse, it is not one file of two
        hundred to skip, it is somebody's planted path. (Security pass of
        2026-09-23, finding 3.)
        """
        directory = self.runs_dir(tenant) / _check_name(suite, "suite")
        paths = tuple(_listed(directory, "*.json"))
        for path in paths:
            self._inside(path, "run")
        return paths

    def stored_paths(self, tenant: str, suite: str) -> tuple[Path, ...]:
        """Every stored document of a suite — its runs, then its baseline — as
        `migrate` rewrites them, each proved to lead inside the store.

        The baseline is here and not left to the caller because it had the
        same gap: `migrate` appended `baseline_path` after only an `exists()`.
        """
        paths = list(self.run_paths(tenant, suite))
        baseline = self.baseline_path(tenant, suite)
        if _exists(baseline):
            paths.append(self._inside(baseline, "baseline"))
        return tuple(paths)

    def read_run(self, ref: RunRef) -> Run:
        path = self.run_path(ref)
        if not _exists(path):
            raise RunNotFoundError(f"run not found: {path}")
        path = self._inside(path, "run")
        run = run_from_json(_document_text(path))
        if run.tenant != ref.tenant:
            raise TenantMismatchError(
                f"the run stored at {path} declares tenant {run.tenant!r} but "
                f"was addressed as {ref.tenant!r}"
            )
        if run.suite != ref.suite:
            raise SuiteMismatchError(
                f"the run stored at {path} declares suite {run.suite!r} but is "
                f"filed under {ref.suite!r}. Promoting it would write "
                f"{run.suite!r}'s baseline, which is the suite the document "
                "names and not the one it was addressed through"
            )
        if key_of(run.created_at, run.config_hash) != ref.key:
            self._refuse_misfiled(ref)
        return run

    def _refuse_misfiled(self, ref: RunRef) -> None:
        """Raise `MisfiledRunError` with the scan's own sentence for this file.

        The scan is read again rather than the sentence rebuilt here, because
        two of its facts are about the directory and not about this file: is a
        file named by the key there, and is the key held by another left-out
        file too. Only a refusal pays for it. (ADR 0040 §5.3)
        """
        listing = self.scan_runs(ref.tenant, ref.suite)
        listed = {other.key for other in listing.runs}
        for misfiled in listing.misfiled:
            if misfiled.stem == ref.key:
                raise MisfiledRunError(
                    f"run {ref.key!r} is filed under a name that is not its "
                    f"key: {misfiled.sentence(listed=misfiled.key in listed)}"
                )
        # The file changed between the read and the scan.
        raise MisfiledRunError(
            f"run {ref.key!r} is filed under a name that is not its key"
        )

    def read_baseline(self, tenant: str, suite: str) -> Run | None:
        path = self.baseline_path(tenant, suite)
        if not _exists(path):
            return None
        path = self._inside(path, "baseline")
        run = run_from_json(_document_text(path))
        if run.tenant != tenant:
            raise TenantMismatchError(
                f"the baseline at {path} declares tenant {run.tenant!r} but was "
                f"read as {tenant!r}"
            )
        if run.suite != suite:
            raise SuiteMismatchError(
                f"the baseline at {path} declares suite {run.suite!r} but was "
                f"read as {suite!r}"
            )
        if run.projected and (
            not run.promoted_at or any(case.responses for case in run.results)
        ):
            raise NotAReferenceError(
                f"the baseline at {path} is a projection of a run nobody "
                "promoted: it carries no promotion time, or answers. A served "
                "projection is for a page, and what stands here is the "
                "projection of the reference promote_baseline returned"
            )
        return run

    def promote_baseline(
        self,
        ref: RunRef,
        expected_config_hash: str,
        *,
        expected_baseline: str | None,
        promoted_at: str,
    ) -> Run:
        # `read_run` already refuses a run addressed through the wrong tenant,
        # and a document that declares another suite — conditions 1 and 7, made
        # as the run is read.
        run = self.read_run(ref)

        # The conditions that answer from the document alone, in the order
        # they are owed. The first is raised and the rest are not looked at, which is
        # what the body this replaced did; the tuple leaves that choice here
        # rather than making it for every backend.
        refusals = refusals_for(run, expected_config_hash)
        if refusals:
            raise refusals[0]

        # Last, and beside the write: every refusal above is about the run and
        # holds whatever the reference, and this one is about what happened to
        # the reference since somebody compared against it. This store has no
        # lock, so the window ADR 0031 leaves open is still open here — what is
        # narrow is the distance between this read and the rename below.
        # (ADR 0031 §2)
        self._refuse_a_moved_baseline(run, expected_baseline)

        self.ensure_layout(run.tenant)
        # The answers do not go into git. `baselines/` is committed, and a
        # baseline is an approved reference of verdicts — promoting a recorded
        # run would put the model's output in somebody's history as a side
        # effect of the most routine action in the product. (ADR 0015 §5)
        # And the signature gets its own time. `created_at` is when the run was
        # measured; a promotion happens once somebody has read it, commonly days
        # later, and until now the document could not tell the two apart.
        # Stamped from what the caller passed — the store reads no clock.
        # (ADR 0014 §3)
        reference = replace(without_responses(run), promoted_at=promoted_at)
        _write_atomic(self.baseline_path(run.tenant, run.suite), run_to_json(reference))
        return reference

    def _refuse_a_moved_baseline(self, run: Run, expected: str | None) -> None:
        """Read the baseline present and raise condition 8's refusal if it is
        not the one the caller compared against.

        The reading is this store's, and so is the window around it; the
        sentence is `refusal_for_a_moved_baseline`'s. What this adds to it is
        the one clause only a file store can write: the path a reader runs
        `git log` against to see what removed a reference.
        """
        moved = refusal_for_a_moved_baseline(
            run,
            self.read_baseline(run.tenant, run.suite),
            expected,
            removed_by=(
                f"git log -- {self.baseline_path(run.tenant, run.suite)} says which"
            ),
        )
        if moved is not None:
            raise moved

    # -- the delete ----------------------------------------------------------- #

    def delete_run(self, ref: RunRef) -> Removal:
        """See the protocol. A plan that only reads, then a removal that raises
        no refusal. (ADR 0044)"""
        # 1. The address, first: without valid names the baseline cannot be read.
        _check_name(ref.tenant, "tenant")
        _check_name(ref.suite, "suite")
        _check_name(ref.key, "run")

        # 2. The baseline. One that cannot be read raises here, with the error
        # its reading raised: could not look is not "not under the baseline".
        self._refuse_a_promoted_run(ref)

        # 3. The run asked for, then 4. the tenant.
        target = self._plan_target(ref)
        replays, unread = self._plan_replays(ref, target)

        # The removal. Leaves first, so an interruption leaves every replay not
        # yet removed chained to `ref` through the ones that survive, and the
        # same call finds it again. Legs before the document, so a run cut off
        # between the two is a finished run with no legs. (ADR 0044 §4)
        doomed = (*replays, target)
        for item in doomed:
            for leg in item.legs:
                leg.unlink(missing_ok=True)
            if item.document is not None:
                item.document.unlink(missing_ok=True)
        for journal in {leg.parent for item in doomed for leg in item.legs}:
            # Only when nothing else is pending, as `complete` does it.
            with suppress(OSError):
                journal.rmdir()
        return Removal(
            run=target.removed,
            replays=tuple(item.removed for item in replays),
            unread=unread,
        )

    def _refuse_a_promoted_run(self, ref: RunRef) -> None:
        """Read the baseline and raise the delete's refusal if it rests on
        `ref.key`. The read is this store's, the sentence is
        `refusal_for_a_promoted_run`'s. (ADR 0044 §3.2)"""
        promoted = refusal_for_a_promoted_run(
            ref, self.read_baseline(ref.tenant, ref.suite)
        )
        if promoted is not None:
            raise promoted

    def _raw_document(self, path: Path) -> Mapping[str, object]:
        """The document under the key asked for, as the scan reads it: parsed,
        and nothing built from it.

        Raises `DocumentRefusedError` for what is not a JSON object, and
        `PathRefusedError` for a link out of the store."""
        text = _document_text(self._inside(path, "run"))
        try:
            raw = json.loads(text)
        except ValueError:
            raise DocumentRefusedError(
                f"{path} is not JSON, so it cannot be shown to be the run its name "
                "says. Removing it by name could remove the wrong document, so "
                "nothing was removed"
            ) from None
        if not isinstance(raw, dict):
            raise DocumentRefusedError(
                f"{path} is JSON but not a document, so it cannot be shown to be "
                "the run its name says. Removing it by name could remove the "
                "wrong document, so nothing was removed"
            )
        return cast(Mapping[str, object], raw)

    def _plan_target(self, ref: RunRef) -> _Doomed:
        """The document under `ref.key`, verified to be that run with the
        scan's light reading so an older schema can be removed, and its legs,
        removed by name. (ADR 0044 §3.3)"""
        path = self.run_path(ref)
        document: Path | None = None
        created_at: str | None = None
        if _exists(path):
            raw = self._raw_document(path)
            tenant, suite = raw.get("tenant"), raw.get("suite")
            if tenant != ref.tenant:
                raise TenantMismatchError(
                    f"the run stored at {path} declares tenant {_shown(tenant)} "
                    f"but was addressed as {ref.tenant!r}, so nothing was removed"
                )
            if suite != ref.suite:
                raise SuiteMismatchError(
                    f"the run stored at {path} declares suite {_shown(suite)} but "
                    f"is filed under {ref.suite!r}, so nothing was removed"
                )
            key = _declared_key(raw)
            if key is None:
                raise KeylessRunError(
                    f"the file filed as run {ref.key} at {path} has no key of its "
                    f"own: {_keyless(raw)}. It cannot be shown to be run "
                    f"{ref.key}, and removing it by name could remove the wrong "
                    "document, so nothing was removed"
                )
            if key != ref.key:
                self._refuse_misfiled(ref)
            created_at = cast(str, raw["created_at"])
            document = path
        legs = self._legs_to_remove(self.journal_dir(ref.tenant, ref.suite), ref.key)
        if created_at is None:
            created_at = next(
                (found for leg in legs if (found := _header_created_at(leg))), None
            )
        return _Doomed(
            removed=RemovedRun(
                ref=ref,
                created_at=created_at,
                legs=len(legs),
                document=document is not None,
            ),
            legs=legs,
            document=document,
        )

    def _legs_to_remove(self, journal: Path, key: str) -> tuple[Path, ...]:
        """Every leg of `key`, by name, each proved to lead inside the store.

        Not verified beyond its name: a leg's name is its key, and a leg nobody
        can read is still that run's. (ADR 0044 §3.3)"""
        legs = tuple(path for _, path in self._legs(journal, key))
        for leg in legs:
            self._inside(leg, "journal")
        return legs

    def _plan_replays(self, ref: RunRef, target: _Doomed) -> tuple[list[_Doomed], int]:
        """Every document of the tenant read for its `rejudged_from`, the chain
        followed down from `ref.key`, and the replays on it in the order they
        go, leaves first. Returned with the count of documents that could not
        be read.

        **The plan trusts neither a file's name nor the address a document
        declares.** What identifies a document is its key and its
        `rejudged_from`, so a replay filed under another name, or declaring
        another tenant or suite than the directory it sits in, is on the chain
        like any other and is removed, with `filed_as` saying where it was. A
        document that puts itself on the chain and has no key cannot be named,
        and refuses the delete. (ADR 0044 §3.4, ruled 2026-10-07)
        """
        read: list[tuple[Path, Mapping[str, object]]] = []
        unread = 0
        for directory in _suite_dirs(self.runs_dir(ref.tenant)):
            for path in _listed(directory, "*.json"):
                if path == target.document:
                    continue
                try:
                    # `scan_runs`' rule: a linked-out file is counted, never
                    # opened.
                    raw = json.loads(
                        self._inside(path, "run").read_text(encoding="utf-8")
                    )
                except (OSError, ValueError):
                    unread += 1
                    continue
                if not isinstance(raw, dict):
                    unread += 1
                    continue
                read.append((path, cast(Mapping[str, object], raw)))

        # Breadth first, one level of the chain per pass: a document joins at
        # the first pass whose chain holds the key its `rejudged_from` names.
        chain = {ref.key}
        levels: list[list[tuple[Path, RemovedRun]]] = []
        on_plan: set[Path] = set()
        while True:
            level = [
                (path, raw)
                for path, raw in read
                if path not in on_plan and _rejudged_from(raw) in chain
            ]
            if not level:
                break
            found = [self._plan_replay(ref, path, raw) for path, raw in level]
            on_plan.update(path for path, _ in found)
            chain |= {removed.ref.key for _, removed in found}
            levels.append(found)

        # Legs last, once the whole plan is known, because whose they are
        # depends on it. Legs are named by a key, so they belong to the
        # document filed under that key. Where such a document stays — a
        # misfiled replay of `K` holds the key of a run that is not on the
        # chain — its legs stay with it: the legs of the document removed would
        # be under the same name, and nothing tells the two apart. Two
        # documents under one key that both go take the legs once. (ADR 0044
        # §5, ruled 2026-10-07)
        doomed: list[_Doomed] = []
        taken: set[Path] = set()
        for path, removed in (pair for level in reversed(levels) for pair in level):
            directory = path.parent
            owner = directory / f"{removed.ref.key}.json"
            legs: tuple[Path, ...] = ()
            if owner in on_plan or not _exists(owner):
                legs = tuple(
                    leg
                    for leg in self._legs_to_remove(
                        directory / PENDING_DIRNAME, removed.ref.key
                    )
                    if leg not in taken
                )
                taken.update(legs)
            doomed.append(
                _Doomed(
                    removed=replace(removed, legs=len(legs)),
                    legs=legs,
                    document=path,
                )
            )
        return doomed, unread

    def _plan_replay(
        self, ref: RunRef, path: Path, raw: Mapping[str, object]
    ) -> tuple[Path, RemovedRun]:
        """One document on the chain: its own key, the address it declares,
        and how it was filed whenever the file's name, that address and its
        key do not all agree. Its legs are counted once the plan is whole.
        (ADR 0044 §1, §3.4)"""
        key = _declared_key(raw)
        if key is None:
            raise KeylessRunError(
                f"{path} is on the chain of run {ref.key}, through its "
                f"rejudged_from, and has no key of its own: {_keyless(raw)}. "
                "What cannot be named is not removed, so nothing was removed"
            )
        filing = Filing(tenant=ref.tenant, suite=path.parent.name, name=path.stem)
        declared = RunRef(
            tenant=_declared(raw, "tenant", filing.tenant),
            suite=_declared(raw, "suite", filing.suite),
            key=key,
        )
        agree = (
            raw.get("tenant") == filing.tenant
            and raw.get("suite") == filing.suite
            and key == filing.name
        )
        return path, RemovedRun(
            ref=declared,
            created_at=cast(str, raw["created_at"]),
            legs=0,
            document=True,
            filed_as=None if agree else filing,
        )

    # -- the register --------------------------------------------------------- #

    def register_path(self, tenant: str, suite: str) -> Path:
        return (
            self.tenant_dir(tenant)
            / REGISTER_DIRNAME
            / f"{_check_name(suite, 'suite')}.jsonl"
        )

    def read_register(self, tenant: str, suite: str) -> Register:
        """Every recorded disposition, in `recorded_at` order.

        The journal's rule for a damaged file (ADR 0017 §3), applied to a
        committed one: an incomplete last line is the one an interrupted write
        leaves, so it is not read and `torn` says so; a line that does not parse
        anywhere else is a corrupt register and is refused by name. Nothing here
        repairs anything — a committed record's bytes are not a command's to
        change. (ADR 0021 §5)

        **A committed register is a hostile document**: anyone who lands a pull
        request writes it, and `log`, `register` and the MCP `log` all read it.
        So a line that parses into something no writer produces is refused by
        name, wherever it sits — `Infinity`, an integer no count could be,
        nesting, a duplicate key, a field of the wrong type, a byte-order mark.
        None of those is a tear, so none of them is forgiven as one, and none of
        them may reach a caller as anything but a `RegisterRefusedError`: a
        traceback there is a bug report handed to whoever reads the log.
        (0.13.0 delta-pass)
        """
        path = self.register_path(tenant, suite)
        if not _exists(path):
            return Register()
        data = self._inside(path, "register").read_bytes()
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise RegisterRefusedError(
                f"{path} is not UTF-8 at byte {exc.start}: digline writes a "
                "register as UTF-8, so these bytes are not one. It is a committed "
                "record, so it is named rather than repaired — restore it from git"
            ) from None
        if text.startswith("﻿"):
            raise RegisterRefusedError(
                f"{path} line 1 begins with a byte-order mark, which digline never "
                "writes: an editor saved the file. A mark is not a torn write, so "
                "it is not forgiven as one — remove it in a commit of its own"
            )
        # `\n` and nothing else. `str.splitlines()` also breaks at NEL (U+0085)
        # and the Unicode line and paragraph separators, which the writer puts
        # down raw inside a string (`ensure_ascii=False`) — so it cut lines
        # digline itself wrote, and read them back as corrupt. (0.13.0 delta-pass)
        lines = text.split("\n")
        if lines and not lines[-1]:
            lines.pop()
        seen: set[str] = set()
        entries: list[RegisterEntry] = []
        torn = False
        for index, line in enumerate(lines):
            if not line.strip():
                continue
            number = index + 1
            try:
                raw = _parse_register_line(line)
            except _MalformedLine as exc:
                raise RegisterRefusedError(
                    Quoted.of(exc, *_malformed(path, number), named=False)
                ) from None
            except ValueError:
                if index == len(lines) - 1:
                    torn = True
                    break
                raise RegisterRefusedError(
                    f"{path} is corrupt at line {number}: a register may only "
                    "be incomplete at its last line, which is the one an "
                    "interrupted write leaves. It is a committed record, so it is "
                    "named rather than repaired — restore the line from git"
                ) from None
            if not isinstance(raw, dict):
                raise RegisterRefusedError(
                    f"{path} line {number} is not a register entry"
                )
            document = cast(Mapping[str, object], raw)
            version = document.get("register_version")
            # Exactly the integer: `True == 1` in Python, and a line claiming
            # format `true` is not a line in format 1.
            if type(version) is not int or version != REGISTER_VERSION:
                raise RegisterRefusedError(
                    f"{path} line {number} is register format {repr(version)[:40]} "
                    f"and this digline reads {REGISTER_VERSION}: a register is a "
                    "format, not a document, so nothing migrates it. Upgrade "
                    "digline to read it"
                )
            if line in seen:
                # A union merge of two branches that both carried this line.
                continue
            seen.add(line)
            try:
                entries.append(_entry_from_dict(document))
            except _MalformedLine as exc:
                raise RegisterRefusedError(
                    Quoted.of(exc, *_malformed(path, number), named=False)
                ) from None
        entries.sort(key=lambda entry: entry.recorded_at)
        return Register(entries=tuple(entries), torn=torn)

    def append_register(self, tenant: str, suite: str, entry: RegisterEntry) -> None:
        """One line after every line already there, flushed and synced.

        Read first, so a register that cannot be read is refused before a byte
        is written. An incomplete last line is refused too: appending after it
        would turn the one damage a reader forgives into the one it refuses. And
        a last line that parses but has lost its newline gets one, so the new
        entry never joins it — the bytes already there stay a prefix of the
        bytes after. (ADR 0021 §5)

        **Containment is established here, unconditionally, and on its own
        line.** It used to be a side effect of a different question: `_inside`
        was reached only inside `if joined:`, where it had been called to read
        the last byte rather than to check anything — and `joined` needs the
        file to already exist. `read_register` above
        returns early on `not path.exists()` for the same reason. Both guards
        therefore hung off `exists()`, which follows a link, so a **dangling**
        symlink at `register/<suite>.jsonl` skipped both and the `O_CREAT` below
        created the file it named, anywhere the user could write.

        The write that creates the register is the ordinary first use of
        `digline register`, so the one write nobody checked was the one
        everybody makes; every later write was checked correctly. That is why
        this survived from the feature's first commit — it is invisible to
        anyone testing an established register.
        """
        path = self.register_path(tenant, suite)
        if self.read_register(tenant, suite).torn:
            raise RegisterRefusedError(
                f"the last line of {path} is incomplete, and a new entry written "
                "after it would leave a corrupt line in the middle of a committed "
                "record. Restore or remove that line in a commit of its own, then "
                "record again"
            )
        self.ensure_layout(tenant)
        path.parent.mkdir(parents=True, exist_ok=True)
        path = self._inside(path, "register")
        joined = _exists(path) and path.stat().st_size > 0
        if joined:
            joined = not path.read_bytes().endswith(b"\n")
        line = json.dumps(
            _entry_to_dict(entry),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        )
        descriptor = os.open(path, os.O_WRONLY | os.O_APPEND | os.O_CREAT, 0o644)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(("\n" if joined else "") + line + "\n")
            handle.flush()
            os.fsync(handle.fileno())

    # -- the journal ---------------------------------------------------------- #

    def journal_dir(self, tenant: str, suite: str) -> Path:
        return self.runs_dir(tenant) / _check_name(suite, "suite") / PENDING_DIRNAME

    def open_journal(self, header: JournalHeader) -> FileJournal:
        """Begin a leg of this run, and refuse if another process holds it.

        The leg number is the first free one, taken with `O_CREAT|O_EXCL` and
        **never retried**: a second resumer that found leg 2 taken and quietly
        wrote leg 3 would call every case the first one has not finished yet, in
        parallel and at the user's expense. Losing the race is a refusal.
        """
        self.ensure_layout(_check_name(header.tenant, "tenant"))
        directory = self.journal_dir(header.tenant, header.suite)
        directory.mkdir(parents=True, exist_ok=True)
        key = _check_name(journal_key(header), "run")
        legs = [leg for leg, _ in self._legs(directory, key)]
        stamped = replace(header, leg=max(legs, default=0) + 1)
        return FileJournal(directory / f"{key}.{stamped.leg}.jsonl", stamped)

    def pending(self, tenant: str, suite: str) -> tuple[Pending, ...]:
        """Every run of this suite that was started and never written.

        Ordered by key, which is chronological because the key begins with the
        slugged `created_at` of the run that started it.
        """
        directory = self.journal_dir(tenant, suite)
        grouped: dict[str, list[tuple[int, Path]]] = {}
        foreign: list[Pending] = []
        for path in _listed(directory, "*.jsonl"):
            match = _LEG_RE.match(path.stem)
            if match is None:
                # Named, never deleted: this directory is digline's, but a file
                # in it holds somebody's paid work until proven otherwise.
                foreign.append(
                    Pending(
                        key=path.name,
                        refusal=(
                            f"{path.name} is not a journal leg: a leg is named "
                            "<run key>.<leg>.jsonl"
                        ),
                    )
                )
                continue
            grouped.setdefault(match["key"], []).append((int(match["leg"]), path))
        found = [
            self._read_journal(tenant, suite, key, sorted(legs))
            for key, legs in sorted(grouped.items())
        ]
        return tuple(sorted([*found, *foreign], key=lambda item: item.key))

    def drop_pending(self, tenant: str, suite: str, key: str) -> None:
        """Remove every leg of one journal. See the protocol for when."""
        directory = self.journal_dir(tenant, suite)
        for _, path in self._legs(directory, key):
            self._inside(path, "journal").unlink(missing_ok=True)
        with suppress(OSError):
            directory.rmdir()

    def _legs(self, directory: Path, key: str) -> list[tuple[int, Path]]:
        legs: list[tuple[int, Path]] = []
        for path in _listed(directory, f"{glob.escape(key)}.*.jsonl"):
            match = _LEG_RE.match(path.stem)
            if match is not None and match["key"] == key:
                legs.append((int(match["leg"]), path))
        return sorted(legs)

    def _read_journal(
        self, tenant: str, suite: str, key: str, legs: Sequence[tuple[int, Path]]
    ) -> Pending:
        """One run's legs, in order, folded into what a resume needs.

        A journal that cannot be read is **returned rather than raised**: the
        caller is surveying, and a survey names what it could not use instead of
        stopping at it — `Listing`'s rule, for the same reason.
        """
        header: JournalHeader | None = None
        done: dict[str, CaseResult] = {}
        causes: dict[str, str] = {}
        spent = CallTotals()
        observed_target = SystemConfig()
        observed_judge = SystemConfig()

        def refused(reason: str) -> Pending:
            return Pending(key=key, refusal=reason, legs=len(legs))

        for leg, path in legs:
            try:
                lines = (
                    self._inside(path, "journal")
                    .read_text(encoding="utf-8")
                    .splitlines()
                )
            except (OSError, ValueError) as exc:
                return refused(f"leg {leg} of {key} cannot be read: {exc}")
            for index, line in enumerate(lines):
                try:
                    raw = cast(Mapping[str, object], json.loads(line))
                except (ValueError, TypeError):
                    if index == len(lines) - 1:
                        # The line the kill interrupted. Every leg of a resumed
                        # run ended in one, so this is expected at the end of
                        # any of them — and only there. (ADR 0017 §3)
                        break
                    return refused(
                        f"leg {leg} of {key} is corrupt at line {index + 1}: a "
                        "journal may only be truncated at its last line, which "
                        "is the one a kill interrupted"
                    )
                kind = raw.get("kind")
                try:
                    if kind == "header":
                        parsed = _header_from_dict(raw)
                        if parsed.journal_version != JOURNAL_VERSION:
                            return refused(
                                f"{key} was written in journal format "
                                f"{parsed.journal_version} and this digline "
                                f"reads {JOURNAL_VERSION}: a journal is a work "
                                "file, not a document, so nothing migrates it. "
                                "Upgrade digline to finish this run, or start "
                                "it again"
                            )
                        if header is None:
                            header = parsed
                        elif parsed.differences(header):
                            return refused(
                                f"leg {leg} of {key} disagrees with leg 1 on "
                                f"{', '.join(parsed.differences(header))}"
                            )
                    elif kind == "observed":
                        observed_target = config_from_dict(
                            cast(Mapping[str, object], raw.get("target_config") or {}),
                            "target_config",
                        )
                        observed_judge = config_from_dict(
                            cast(Mapping[str, object], raw.get("judge_config") or {}),
                            "judge_config",
                        )
                    elif kind == "case":
                        result = case_from_dict(
                            cast(Mapping[str, object], raw["case"]), redacted=False
                        )
                        # Last record wins: a case appears twice only when it was
                        # retried, and the file is append-only.
                        done[result.case_id] = result
                        causes[result.case_id] = str(raw.get("cause") or "")
                        # And **every** record counts towards the bill, not the
                        # last one per case: `done` keeps one outcome because a
                        # case has one, while a case that was paid for twice
                        # cost twice. Mandatory at journal format 2 — a `case`
                        # line without it is malformed and the leg is refused,
                        # rather than resumed with a leg's money missing.
                        spent = spent + totals_from_dict(raw["usage"], "journal")
                    else:
                        return refused(
                            f"leg {leg} of {key} holds a record of kind "
                            f"{kind!r} at line {index + 1}, which this digline "
                            "does not know"
                        )
                except (KeyError, ValueError, TypeError) as exc:
                    return refused(
                        f"leg {leg} of {key} is malformed at line {index + 1}: {exc}"
                    )
        if header is None:
            return refused(f"{key} has no header: the first line of leg 1 is one")
        errored = frozenset(
            case_id
            for case_id, result in done.items()
            if any(verdict.status == "error" for verdict in result.verdicts)
        )
        return Pending(
            key=key,
            header=header,
            legs=len(legs),
            spent=spent,
            done=done,
            errored=errored,
            causes={
                case_id: cast(Cause, causes.get(case_id, "")) for case_id in errored
            },
            observed_target=observed_target,
            observed_judge=observed_judge,
            finished=_exists(
                self.run_path(RunRef(tenant=tenant, suite=suite, key=key))
            ),
        )


_OUTCOME_FIELDS = (
    "regressed",
    "improved",
    "unchanged",
    "new",
    "missing",
    "errored",
    "unjudged",
    "suspended",
    "within_noise",
    "on_the_line",
)
_OUTCOME_FLAGS = (
    "worse",
    "canary_moved",
    "config_changed",
    "artifacts_changed",
    "target_config_changed",
    "judge_config_changed",
    "rejudged",
)


def _entry_to_dict(entry: RegisterEntry) -> dict[str, object]:
    """The register's line: ADR 0021 §3's shape, and nothing else it could hold."""
    outcome = entry.outcome
    return {
        "register_version": REGISTER_VERSION,
        "recorded_at": entry.recorded_at,
        "digline_version": entry.digline_version,
        "disposition": entry.disposition,
        "run": {
            "key": entry.run_key,
            "created_at": entry.run_created_at,
            "config_hash": entry.run_config_hash,
            "environment": entry.run_environment,
            "digline_version": entry.run_digline_version,
            "rejudged": entry.run_rejudged,
        },
        "baseline": {
            "key": entry.baseline_key,
            "config_hash": entry.baseline_config_hash,
            # Null where it was not recorded, never a date filled in from git.
            "promoted_at": entry.baseline_promoted_at or None,
        },
        "outcome": {
            **{name: int(getattr(outcome, name)) for name in _OUTCOME_FIELDS},
            **{name: bool(getattr(outcome, name)) for name in _OUTCOME_FLAGS},
        },
        "exit_code": entry.exit_code,
    }


class _MalformedLine(Exception):
    """A register line that parses into something no writer produces.

    **Deliberately not a `ValueError`.** `read_register` forgives a `ValueError`
    on the last line as a torn write, and nothing raised as this is a tear: an
    `Infinity` on the last line is a hostile line, not an interrupted one.
    """


#: Wider than any count or exit code a register holds, and far short of the
#: thousands of digits Python refuses to convert — which it refuses with a
#: `ValueError`, so a line carrying them read as torn. (0.13.0 delta-pass)
_MAX_DIGITS = 18


def _refuse_constant(name: str) -> object:
    raise _MalformedLine(f"{name} is not a value a register line can hold")


def _bounded_int(digits: str) -> int:
    length = len(digits.lstrip("-"))
    if length > _MAX_DIGITS:
        raise _MalformedLine(
            f"it holds an integer of {length} digits, which is no count"
        )
    return int(digits)


def _no_duplicate_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
    """Last-wins is `json.loads`'s default, and it let one line say both
    `accepted` and `rejected` and be read as whichever came second."""
    found: dict[str, object] = {}
    for key, value in pairs:
        if key in found:
            raise _MalformedLine(f"it has a duplicate key {key[:40]!r}")
        found[key] = value
    return found


def _parse_register_line(line: str) -> object:
    """`json.loads`, held to what a writer produces.

    A `ValueError` still means the line does not parse — which is what a torn
    tail is. Everything a hostile line can do *besides* not parsing raises
    `_MalformedLine` instead, including the `RecursionError` deep nesting drives
    the decoder into.
    """
    try:
        return json.loads(
            line,
            parse_constant=_refuse_constant,
            parse_int=_bounded_int,
            object_pairs_hook=_no_duplicate_keys,
        )
    except RecursionError:
        raise _MalformedLine("it is nested deeper than any register line") from None


def _malformed(path: Path, number: int) -> tuple[str, str]:
    """Digline's words before and after the reason a line is malformed."""
    return (
        f"{path} line {number} is malformed: ",
        ". It is a committed record, so it is named rather than repaired — "
        "restore the line from git",
    )


_MISSING = object()


def _kind(value: object) -> str:
    """What a field held, in JSON's words, and never the value itself: a refusal
    is printed, and the value is text a stranger wrote."""
    if value is _MISSING:
        return "nothing"
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "a boolean"
    if isinstance(value, int):
        return "a whole number"
    if isinstance(value, float):
        return "a decimal number"
    if isinstance(value, str):
        return "a string"
    if isinstance(value, list):
        return "a list"
    return "an object"


def _where(section: str, key: str) -> str:
    return f"{section}.{key}" if section else key


def _section(raw: Mapping[str, object], name: str) -> Mapping[str, object]:
    found = raw.get(name, _MISSING)
    if not isinstance(found, dict):
        raise _MalformedLine(f"{name} must be an object, got {_kind(found)}")
    return cast(Mapping[str, object], found)


def _text(
    fields: Mapping[str, object], key: str, section: str = "", *, optional: bool = False
) -> str:
    value = fields.get(key, _MISSING)
    if optional and (value is _MISSING or value is None):
        return ""
    if not isinstance(value, str):
        raise _MalformedLine(
            f"{_where(section, key)} must be a string, got {_kind(value)}"
        )
    return value


def _flag(fields: Mapping[str, object], key: str, section: str) -> bool:
    value = fields.get(key, _MISSING)
    if not isinstance(value, bool):
        raise _MalformedLine(
            f"{_where(section, key)} must be true or false, got {_kind(value)}"
        )
    return value


def _whole(fields: Mapping[str, object], key: str, section: str = "") -> int:
    value = fields.get(key, _MISSING)
    # `bool` is an `int` in Python, and `true` is not a count.
    if isinstance(value, bool) or not isinstance(value, int):
        raise _MalformedLine(
            f"{_where(section, key)} must be a whole number, got {_kind(value)}"
        )
    return value


def _entry_from_dict(raw: Mapping[str, object]) -> RegisterEntry:
    """A line held to the types `_entry_to_dict` writes: refused, never coerced.

    `bool("false")` is `True` and `int(2.9)` is `2`, so a reader that converts
    reads a different record than the bytes hold — which is the one thing a
    committed record must never do, and what ADR 0021 §5 already said: a line
    this digline cannot read is refused by name. (0.13.0 delta-pass)
    """
    run = _section(raw, "run")
    baseline = _section(raw, "baseline")
    outcome = _section(raw, "outcome")
    disposition = raw.get("disposition", _MISSING)
    if disposition not in DISPOSITIONS:
        # A string is named as one and not quoted: the refusal is printed, and
        # the value is text a stranger wrote.
        got = "another string" if isinstance(disposition, str) else _kind(disposition)
        raise _MalformedLine(
            f"disposition must be one of {', '.join(DISPOSITIONS)}, got {got}"
        )
    return RegisterEntry(
        recorded_at=_text(raw, "recorded_at"),
        digline_version=_text(raw, "digline_version", optional=True),
        disposition=disposition,
        run_key=_text(run, "key", "run"),
        run_created_at=_text(run, "created_at", "run"),
        run_config_hash=_text(run, "config_hash", "run"),
        run_environment=_text(run, "environment", "run"),
        run_digline_version=_text(run, "digline_version", "run", optional=True),
        run_rejudged=_flag(run, "rejudged", "run"),
        baseline_key=_text(baseline, "key", "baseline"),
        baseline_config_hash=_text(baseline, "config_hash", "baseline"),
        baseline_promoted_at=_text(baseline, "promoted_at", "baseline", optional=True),
        outcome=RecordedOutcome(
            **{name: _whole(outcome, name, "outcome") for name in _OUTCOME_FIELDS},
            **{name: _flag(outcome, name, "outcome") for name in _OUTCOME_FLAGS},
        ),
        exit_code=_whole(raw, "exit_code"),
    )


#: Where journals live: a dot-directory under the suite's runs, so the generated
#: `.gitignore` already covers it (`*/runs/` ignores the directory and
#: everything beneath it) and every `*.json` listing in this module steps over it.
#: A journal is not a document: nothing lists it, compares it, migrates it or
#: renders it. (ADR 0017 §2)
PENDING_DIRNAME = ".pending"

_LEG_RE = re.compile(r"^(?P<key>.+)\.(?P<leg>[0-9]+)$")


def journal_key(header: JournalHeader) -> str:
    """The key a journal — and therefore the run it becomes — is named after.

    `key_of` again, over the header instead of the run — the same rule
    `write_run` is held to — and that is the point: a resumed run keeps the
    original `created_at` (ADR 0017 §8), so it is written to exactly the file
    the killed run was always going to write.
    """
    return key_of(header.created_at, header.config_hash)


def _header_to_dict(header: JournalHeader) -> dict[str, object]:
    return {
        "kind": "header",
        "journal_version": header.journal_version,
        "leg": header.leg,
        "tenant": header.tenant,
        "environment": header.environment,
        "suite": header.suite,
        "config_hash": header.config_hash,
        "cases_digest": header.cases_digest,
        "created_at": header.created_at,
        "started_at": header.started_at,
        "digline_version": header.digline_version,
        "record_responses": header.record_responses,
        "git_commit": header.git_commit,
        "artifacts": dict(sorted(header.artifacts.items())),
        "pinned": sorted(header.pinned),
        "target_config": config_to_dict(header.target_config),
        "judge_config": config_to_dict(header.judge_config),
    }


def _header_from_dict(raw: Mapping[str, object]) -> JournalHeader:
    commit = raw.get("git_commit")
    return JournalHeader(
        tenant=str(raw["tenant"]),
        environment=str(raw["environment"]),
        suite=str(raw["suite"]),
        config_hash=str(raw["config_hash"]),
        cases_digest=str(raw["cases_digest"]),
        created_at=str(raw["created_at"]),
        started_at=str(raw["started_at"]),
        digline_version=str(raw["digline_version"]),
        # Declared, not converted: `bool("false")` is true, and a resumed run
        # would have recorded answers the run it continues did not. (#379)
        record_responses=declared_boolean(raw, "record_responses", "journal header"),
        git_commit=None if commit is None else str(commit),
        pinned=tuple(
            sorted(
                str(path) for path in cast("Sequence[object]", raw.get("pinned") or ())
            )
        ),
        artifacts={
            str(path): str(sha)
            for path, sha in cast(
                Mapping[str, object], raw.get("artifacts") or {}
            ).items()
        },
        target_config=config_from_dict(
            cast(Mapping[str, object], raw.get("target_config") or {}), "target_config"
        ),
        judge_config=config_from_dict(
            cast(Mapping[str, object], raw.get("judge_config") or {}), "judge_config"
        ),
        # Declared, not converted: `int()` read "3" and 3.9 as format 3. (#350)
        journal_version=declared_integer(raw, "journal_version"),
        leg=declared_integer(raw, "leg"),
    )


def _line(payload: Mapping[str, object]) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n"


class FileJournal:
    """One leg of a run, appended to as the run goes.

    Opened with `O_CREAT|O_EXCL`, which is the entire concurrency story: a
    second process resuming the same run finds the leg taken and is refused by
    name. No lock file — the process this exists for is one that was killed, and
    a lock it could not release would block the rescue. (ADR 0017 §5)
    """

    def __init__(self, path: Path, header: JournalHeader) -> None:
        self._path = path
        self._header = header
        try:
            descriptor = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        except FileExistsError as exc:
            raise JournalBusyError(
                f"leg {header.leg} of run {journal_key(header)} is already being "
                f"written at {path}: another digline is resuming this run. Wait "
                "for it, or look at what it is doing before starting a second "
                "one — two processes resuming one run would both call the cases "
                "neither has finished"
            ) from exc
        self._handle = os.fdopen(descriptor, "w", encoding="utf-8")
        # Distinct from `SystemConfig()`, which is a legitimate observation:
        # *nothing observed yet* must not compare equal to *observed nothing*,
        # or the first case of a run that declares no configuration would write
        # an observation record saying so.
        self._seen: tuple[SystemConfig, SystemConfig] | None = None
        self._write(_header_to_dict(header))

    @property
    def key(self) -> str:
        return journal_key(self._header)

    @property
    def leg(self) -> int:
        return self._header.leg

    @property
    def path(self) -> Path:
        return self._path

    def _write(self, payload: Mapping[str, object]) -> None:
        """One record, on disk before this returns.

        `flush` would survive a kill; `fsync` is here because the incident that
        produced this feature was memory pressure on a whole machine, and the
        syscall costs microseconds against a case that cost a network call. The
        one thing this file may not do is be fast and empty. (ADR 0017 §3)
        """
        self._handle.write(_line(payload))
        self._handle.flush()
        os.fsync(self._handle.fileno())

    def append(self, progress: CaseProgress) -> None:
        observed = (progress.observed_target, progress.observed_judge)
        if observed != self._seen:
            # Written when it changes, which in an uninterrupted run means once:
            # after the first case that revealed an identity. It is what a
            # resume seeds the target from, so an alias that rolls across the
            # seam raises instead of being averaged. (ADR 0017 §7)
            self._seen = observed
            self._write(
                {
                    "kind": "observed",
                    "target_config": config_to_dict(progress.observed_target),
                    "judge_config": config_to_dict(progress.observed_judge),
                }
            )
        self._write(
            {
                "kind": "case",
                "cause": progress.cause,
                "case": case_to_dict(progress.result, redacted=False),
                # What this case's calls consumed, written whatever the suite
                # records. It is the journal's own fact about work already paid
                # for, not a recording of the answer: a resume that could not
                # add up the legs it did not run would write a document whose
                # bill omits them, and omit them in silence. (ADR 0025 §11)
                "usage": totals_to_dict(progress.usage),
            }
        )

    def complete(self) -> None:
        """The run is written; every leg goes."""
        self._handle.close()
        directory = self._path.parent
        # `glob`, not `_listed`, and on purpose: the run file is already
        # written, so a refusal here would report a finished run as failed.
        # A leg this cannot see stays on disk, and `pending` names it as
        # finished and removes it once the directory can be read. (#365)
        for leg in sorted(directory.glob(f"{glob.escape(self.key)}.*.jsonl")):
            leg.unlink(missing_ok=True)
        # Only when nothing else is pending: another run of the same suite may
        # be journalling right now.
        with suppress(OSError):
            directory.rmdir()
